### PR TITLE
Fix dead README links to C++ API example package

### LINKED ISSUE #100: Dead links in README
The example packaged linked to in the "C++ API" section no longer seems to exist.

### PR DESCRIPTION
**Pull request by Lenostatos**
Fixes #100.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! I am afraid that if we want to make this work on CRAN as well (https://cran.rstudio.com/web/packages/progress/readme/README.html), then we'll have to use absolute links. Or omit the links completely.

**Comment by Lenostatos** [comment]
I understand. I didn't think of the CRAN version.
Should I change the links to absolute links to GitHub? I don't know how to link to the files on CRAN and whether this is possible in the first place (e.g. I tried https://cran.rstudio.com/web/packages/progress/tests/testthat/progresstest/src/test.cpp but got a 404).

**Comment by gaborcsardi** [comment]
Yeah, I think an absolute link as `https://github.com/r-lib/progress/blob/HEAD/tests/testthat/progresstest/src/test.cpp` should be fine. Thanks!

**Comment by Lenostatos** [comment]
Alright, did ti!

Just out of curiosity: Why `.../blob/HEAD/...` instead of `.../blob/master/...`? Does it make a difference? I tried to google it but couldn't find anything conclusive on the matter.

**Comment by gaborcsardi** [comment]
Thanks! `HEAD` will link to the default branch, which is currently `master`, but we might change it later.

**Comment by Lenostatos** [comment]
I see. Thanks!

**Pull request merged**
